### ISSUE TITLE
Empty warehouse

### ISSUE THREAD

**Issue by LAB123-tech** [dsb-ifi/SPiT#1]
This work is truly inspiring, and I look forward to seeing the code released soon. I hope the author will consider open-sourcing it in the near future.

**Comment by mariuaas** [comment]
Hi, thank you for the interest! The code will be out shortly, along with weights for all models.

**Comment by YifanLiang-hust** [comment]
It has been two weeks...

**Comment by mariuaas** [comment]
@BRONYA-818 @LAB123-tech Thanks again for your patience. 
The initial code is now available, along with model weights for most of the models. See the `README.md` for details.

Stay tuned for more examples and updates.
